name: Native docker image release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Native Clean package
        run: |
          chmod +x mvnw
          ./mvnw clean package -Pnative

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        run: docker build -f ./src/main/docker/Dockerfile.native-micro . -t oleksiimyronchenko/cat8rat-cat-service:latest

      - name: Docker tag
        run: docker tag oleksiimyronchenko/cat8rat-cat-service:latest  oleksiimyronchenko/cat8rat-cat-service:$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Docker push version
        run: |
          docker push oleksiimyronchenko/cat8rat-cat-service:latest
          docker push oleksiimyronchenko/cat8rat-cat-service:$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)




