# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      EMAIL_GITHUB: ${{ secrets.EMAIL_GITHUB }}
      USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install SSH Key
        # You may pin to the exact commit or the version.
        # uses: shimataro/ssh-key-action@3c9b0fc6f2d223b8450b02a0445f526350fc73e0
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          # SSH private key
          key: ${{ secrets.ED_GITHUB_PK }}
          # public keys of SSH servers
          known_hosts: ${{ secrets.ED_KNOWN_HOSTS }}

      - name: Configure Git user
        run: |
          git config user.email $EMAIL_GITHUB
          git config user.name $USERNAME_GITHUB

      - name: Release
        run: |
          chmod +x mvnw
          ./mvnw --batch-mode release:prepare
