# This is a basic workflow to help you get started with Actions

name: Native docker image release

# Controls when the workflow will run
on:
  push:
  create:
  workflow_dispatch:

jobs:
  build: #should run only on created tags, i.e. maven release
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Native Clean package
        run: |
          chmod +x mvnw
          ./mvnw clean package -Pnative

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        run: docker build -f ./src/main/docker/Dockerfile.native-micro . -t oleksiimyronchenko/cat8rat:$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Docker push version
        run: docker push oleksiimyronchenko/cat8rat:$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)



